# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# FluidHelloWorld build for CI

pr:
- main

steps:
- task: UseNode@1
  displayName: Use Node 12.x
  inputs: 
    version: 12.x
- task: Npm@1
  displayName: Install
  inputs:
    command: 'custom'
    customCommand: 'install'
- task: Npm@1
  displayName: Build
  inputs:
    command: 'custom'
    customCommand: 'run build'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)/dist
    includeRootFolder: false
- task: CopyFiles@1
  inputs:
    Contents: 'dist/*.zip' 
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs: 
    PathtoPublish: $(Build.ArtifactStagingDirectory)/dist 
    ArtifactName: 'www' 
  
